// Licensed to ObjectStyle LLC under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ObjectStyle LLC licenses
// this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

:bq-header: _index/header.html

= Bq tool Documentation

== What is bq?

bq is a command line interactive tool that allows creating and managing Bootique projects.

== Installation

=== MacOS

`bq` available via Homebrew package manager. All you need in order to install `bq` on MacOS is to run:

[source,bash]
----
brew install bootique-tools/repo/bq
----

=== Linux

==== CentOS
To install `bq` on CentOS you need to

* add bintray repo to your yum sources:
+
[source,shell]
----
wget https://bintray.com/bootique/bq-rpm/rpm -O bintray-bootique-bq-rpm.repo
sudo mv bintray-bootique-bq-rpm.repo /etc/yum.repos.d/
----
* run:
+
[source,bash]
----
yum install bq
----

==== Ubuntu
Installation process is similar to CentOS.

* Add bintray repo to apt sources:
+
[source,bash]
----
echo "deb [trusted=yes] https://dl.bintray.com/bootique/bq-deb vivid main" | sudo tee -a /etc/apt/sources.list
----
* Install:
+
[source,bash]
----
apt-get update
apt-get install bq
----

=== Windows

Windows binary will be distributed with Chocolatey package manager, but this is not implemented yet.
For now, you could download `nupkg` directly from https://bintray.com/bootique/bq/bq/view/files[Bintray].
Use following command to install this package directly:

[source,bash]
----
choco install bq.portable.{VERSION}.nupkg
----

== Usage

Running BQ in an interactive mode:

[source,bash]
----
$ bq
----

If everything setup correctly you should see welcome banner with some general information about the tool.
To see all available commands you could use `help` command.

To exit from the `bq` shell run `exit`.

=== Maven

Maven toolchain is set by default.

1. new multimodule project:
+
[source,bash]
----
new parent io.bootique.test:test:1.0
----

2. new runnable app:
+
[source,bash]
----
new app io.bootique.test:test-app:1.0
----

3. new module:
+
[source,bash]
----
new module io.bootique.test:test-module:1.0
----

=== Gradle

To use Gradle as your build tool you need to set it in `bq` config:

[source,bash]
----
config toolchain gradle
----

Available commands are same as in <<Maven>> case.
