// Licensed to ObjectStyle LLC under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ObjectStyle LLC licenses
// this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

:bq-header: _index/header.html

= Bq tool Documentation

== What is bq?

bq is a command line interactive tool that allows creating and managing Bootique projects.

== Installation

=== MacOS

`bq` available via Homebrew package manager. All you need in order to install `bq` on MacOS is to run:

[source,bash]
----
brew install bootique-tools/repo/bq
----

=== Windows

Windows binary is distributed with https://chocolatey.org[Chocolatey] package manager.
Use following command to install `bq.portable` package:

[source,bash]
----
choco install bq.portable
----

And here is how to upgrade `bq` to the latest version:

[source,bash]
----
choco upgrade bq.portable
----

=== Linux

==== Ubuntu

* Download the latest release from the GitHub:
+
[source,bash]
----
wget https://github.com/bootique/bootique-tool/releases/download/v0.101/bq-0.101.deb
----
* Install:
+
[source,bash]
----
sudo apt install ./bq-0.101.deb
----

==== CentOS

To install `bq` on CentOS you need to

* Download the latest release from the GitHub:
+
[source,bash]
----
wget https://github.com/bootique/bootique-tool/releases/download/v0.101/bq-0.101.x86_64.rpm
----
* Install:
+
[source,bash]
----
sudo yum install bq-0.10
1.x86_64.rpm
----


== Usage

Running BQ in an interactive mode:

[source,bash]
----
$ bq
----

If everything setup correctly you should see welcome banner with some general information about the tool.
To see all available commands you could use `help` command.

To exit from the `bq` shell run `exit`.

=== Maven

Maven toolchain is set by default.

1. new multimodule project:
+
[source,bash]
----
new parent io.bootique.test:test:1.0
----

2. new runnable app:
+
[source,bash]
----
new app io.bootique.test:test-app:1.0
----

3. new module:
+
[source,bash]
----
new module io.bootique.test:test-module:1.0
----

=== Gradle

To use Gradle as your build tool you need to set it in `bq` config:

[source,bash]
----
config toolchain gradle
----

Available commands are same as in <<Maven>> case.
