name: deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  # Prepares a new GitHub release for the tag and exposes required variables for dependent jobs
  prepare-release:
    name: Create Release
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      version: ${{ steps.vars.outputs.version }}
      graalvm_version: ${{ steps.vars.outputs.graalvm_version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # NOTE: graalvm_version should be in sync with the native-image plugin version in the pom.xml
      - name: Set Version
        id: vars
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/*/}
          echo ::set-output name=tag::${RELEASE_TAG}
          echo ::set-output name=version::${RELEASE_TAG:1}
          echo ::set-output name=graalvm_version::21.3.0.java11

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          release_name: Release ${{ steps.vars.outputs.tag }}
          body: |
            BQ tool release ${{ steps.vars.outputs.tag }} binaries

          draft: true
          prerelease: false

  # Deploy Linux .deb and .rpm packages
  deploy-linux:
    name: Deploy Linux binaries
    needs: prepare-release
    runs-on: ubuntu-20.04
    continue-on-error: true

    steps:
      - name: Checkout...
        uses: actions/checkout@v1

      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: ${{ needs.prepare-release.outputs.graalvm_version }}

      - name: Install native-image component
        run: gu install native-image

      - name: Retrieve mvn repo cache...
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: m2-cache-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: m2-cache

      - name: Build native-image
        run: mvn package -Pnative-image -DskipTests

      - name: Build linux native packages...
        run: ./deploy/linux.sh

      - name: Upload deb package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare-release.outputs.upload_url }}
          asset_path: ./bootique-tool/target/bq-${{ needs.prepare-release.outputs.version }}.deb
          asset_name: bq-${{ needs.prepare-release.outputs.version }}.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare-release.outputs.upload_url }}
          asset_path: ./bootique-tool/target/bq-${{ needs.prepare-release.outputs.version }}-1.x86_64.rpm
          asset_name: bq-${{ needs.prepare-release.outputs.version }}.x86_64.rpm
          asset_content_type: application/x-rpm

  # Deploy MacOS package and update homebrew repo link
  deploy-macos:
    name: Deploy MacOS binaries
    needs: prepare-release
    runs-on: macos-latest
    continue-on-error: true

    steps:
      - name: Checkout...
        uses: actions/checkout@v1

      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: ${{ needs.prepare-release.outputs.graalvm_version }}

      - name: Install native-image component
        run: gu install native-image

      - name: Retrieve mvn repo cache...
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: m2-cache-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: m2-cache

      - name: Build MacOS native packages...
        run: mvn package -Pnative-image,assembly-mac -DskipTests

      - name: Upload MacOS package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare-release.outputs.upload_url }}
          asset_path: ./bootique-tool/target/bq-${{ needs.prepare-release.outputs.version }}.zip
          asset_name: bq-${{ needs.prepare-release.outputs.version }}.macos.zip
          asset_content_type: application/zip

      - name: Update Homebrew repo
        run: ./deploy/update-homebrew.sh
        shell: bash
        env:
          TAG: ${{ needs.prepare-release.outputs.tag }}
          VERSION: ${{ needs.prepare-release.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_UPDATE_TOKEN }}

  # Deploy Windows package to Chocolatey and GitHub
  deploy-win:
    name: Deploy Windows binaries
    needs: prepare-release
    runs-on: windows-2019
    continue-on-error: true

    steps:
      - name: Checkout...
        uses: actions/checkout@v1

      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: ${{ needs.prepare-release.outputs.graalvm_version }}

      - name: Install native-image component
        run: gu.cmd install native-image

      - name: Install Win SDK
        run: |
          choco install visualstudio2017-workload-vctools

      - name: Retrieve mvn repo cache...
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: m2-cache-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: m2-cache

      - name: Build Native Image
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          mvn package -Pnative-image,assembly-win -DskipTests

      - name: Choco Pack
        shell: pwsh
        run: |
          Set-Location -Path .\bootique-tool\target\bq-win.portable\bq-win.portable\
          Choco Pack

      - name: Upload Windows package
        uses: actions/upload-release-asset@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare-release.outputs.upload_url }}
          asset_path: .\bootique-tool\target\bq.exe
          asset_name: bq-${{ needs.prepare-release.outputs.version }}.win.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload Choco package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare-release.outputs.upload_url }}
          asset_path: .\bootique-tool\target\bq-win.portable\bq-win.portable\bq.portable.${{ needs.prepare-release.outputs.version }}.nupkg
          asset_name: bq-${{ needs.prepare-release.outputs.version }}.portable.win.nupkg
          asset_content_type: application/zip

      - name: Deploy Choco package
        shell: pwsh
        run: |
          Set-Location -Path .\bootique-tool\target\bq-win.portable\bq-win.portable\
          choco apikey --key ${{ secrets.CHOCO_APIKEY }} --source https://push.chocolatey.org/
          choco push bq.portable.${{ needs.prepare-release.outputs.version }}.nupkg --source https://push.chocolatey.org/