name: verify

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest ]

    steps:
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '22.1.0.java11'

      - name: Install native-image component
        run: gu install native-image

      - name: Checkout...
        uses: actions/checkout@v2

      - name: Retrieve mvn repo cache...
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: m2-cache-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: m2-cache

      - name: Build and test...
        run: mvn clean package -Pnative-image

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-binary
          path: ./bootique-tool/target/bq
          if-no-files-found: error